import express from "express";
import * as loansController from "./loans.controller.js";
import * as installmentsController from "../installments/installments.controller.js";
import * as paymentsController from "../payments/payments.controller.js";
const router = express.Router();
router.get("/", loansController.getLoans);
router.post("/", loansController.createLoan);
router.get("/:id/installments", installmentsController.getInstallmentsByLoanId);
router.post("/:id/payments", paymentsController.makePayment);
router.get("/:id/payments", paymentsController.getPaymentsByLoanId);
router.get("/:id", loansController.getLoan);
export default router;