import { getCustomers, getCustomer, getCustomerWithKeyword, createCustomer, updateCustomer, getCustomerProfile, getCustomersActiveLoans, getCustomersInactiveLoans, getAllActiveLoans, getAllInactiveLoans} from "../controllers/customers.controller.js";
import express from "express";
const router = express.Router();
router.get("/", getCustomers);
router.get("/search", getCustomerWithKeyword);
router.get("/loans/active", getAllActiveLoans);
router.get("/loans/inactive", getAllInactiveLoans);
router.get("/:id/profile", getCustomerProfile);
router.get("/:id/loans/active", getCustomersActiveLoans);
router.get("/:id/loans/inactive", getCustomersInactiveLoans);
router.get("/:id", getCustomer);
router.post("/", createCustomer);
router.put("/:id", updateCustomer);
export default router;