const styles = {
  wrapper: {
    display: "flex",
    minHeight: "100vh",
    background: "#f8fafc",
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  right: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px",
  },
  card: {
    width: "100%",
    maxWidth: "400px",
    padding: "28px",
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(15, 23, 42, 0.08)",
  },
  logoRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "16px",
    fontSize: "18px",
    fontWeight: 700,
  },
  logoIcon: { fontWeight: 800 },
  formTitle: { margin: "0 0 16px", fontSize: "24px", fontWeight: 700 },
  desc: { margin: "0 0 20px", color: "#64748b", fontSize: "14px", lineHeight: 1.5 },
  input: {
    width: "100%",
    boxSizing: "border-box",
    marginBottom: "16px",
    padding: "12px",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    fontSize: "15px",
  },
  button: {
    width: "100%",
    marginBottom: "20px",
    padding: "12px",
    border: 0,
    borderRadius: "6px",
    background: "#000",
    color: "#fff",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
  },
  footer: { margin: 0, textAlign: "center", color: "#64748b", fontSize: "14px" },
  footerLink: { marginLeft: "8px", color: "#000", fontWeight: 600, cursor: "pointer" },
};

export default styles;
